### ISSUE TITLE
Please add License

### ISSUE THREAD

**Issue by ezeql** [ethanresnick/twilio-ivr#56]
could you please add a license on this repo?  I suggest MIT, as it is a versatile and open license popular in OSS. 
Awesome lib btw. Thank you.

**Comment by ethanresnick** [comment]
Thanks for raising this. I'm leaning toward the LGPL. Would that work for your use case?

**Comment by ezeql** [comment]
I think most users including myself would prefer MIT.

**Comment by ezeql** [comment]
https://choosealicense.com/licenses/ may be useful

**Comment by ethanresnick** [comment]
@ezeql What is it about MIT that you prefer?

I like the LGPL because most consumers, who just use the library (e.g. as part of a business app), can keep their source code private, while people forking the library itself have to give their changes back to the community.
